# Generated by Django 5.0.2 on 2024-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('type', models.CharField(choices=[('em', 'emballé'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=2)),
            ],
        ),
    ]
